global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq1"
    static_configs:
      - targets: ["rabbit1:15692"]

  - job_name: "rabbitmq2"
    static_configs:
      - targets: ["rabbit2:15692"]

  - job_name: "rabbitmq3"
    static_configs:
      - targets: ["rabbit3:15692"]
